namespace ZenCode.Lexer.Model;

public enum TokenType
{
    None = 0,
    Addition,
    And,
    Assignment,
    Boolean,
    Comma,
    Division,
    Else,
    ElseIf,
    Equals,
    Exponentiation,
    Float,
    GreaterThan,
    GreaterThanOrEqual,
    Identifier,
    If,
    Integer,
    LeftBrace,
    LeftBracket,
    LeftParenthesis,
    LessThan,
    LessThanOrEqual,
    Modulus,
    Multiplication,
    Not,
    NotEquals,
    Or,
    Print,
    RightBrace,
    RightBracket,
    RightParenthesis,
    String,
    Subtraction,
    Var,
    While,
}