namespace ZenCode.Lexer.Model;

public enum TokenType
{
    Addition,
    And,
    Assignment,
    Boolean,
    Comma,
    Division,
    Equals,
    Exponentiation,
    Float,
    GreaterThan,
    GreaterThanOrEqual,
    Identifier,
    Integer,
    LeftBracket,
    LeftParenthesis,
    LessThan,
    LessThanOrEqual,
    Modulus,
    Multiplication,
    Not,
    NotEquals,
    Or,
    RightBracket,
    RightParenthesis,
    String,
    Subtraction,
}